matrix:
  include:
    - language: python
      python: 3.6
      install:
        - pip install -r requirements.txt
      script:
        - python cx.py $Server $CxUsername $CxPassword $ClientSecret $ProjectName $TeamName $PresetName $FolderExclusions $FileExclusions $TRAVIS_BUILD_DIR $HighThreshold $MediumThreshold $LowThreshold